### ISSUE TITLE
How to open the console command , hidapitester command not found

### ISSUE THREAD

**Issue by Chakib-Temal** [todbot/hidapitester#1]
Hi

i'm on linux Ubuntu 16.04 and i'm trying to run the hidApiTester in my Terminal 

i followed all step 

1--
chakib@chakib-temal:~/HIDTESTER$ git clone https://github.com/libusb/hidapi
Cloning into 'hidapi'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 2022 (delta 1), reused 1 (delta 0), pack-reused 2015
Receiving objects: 100% (2022/2022), 2.63 MiB | 1.60 MiB/s, done.
Resolving deltas: 100% (1311/1311), done.
Checking connectivity... done.
2--
chakib@chakib-temal:~/HIDTESTER$ git clone https://github.com/todbot/hidapitester
Cloning into 'hidapitester'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 101 (delta 53), reused 67 (delta 24), pack-reused 0
Receiving objects: 100% (101/101), 682.88 KiB | 0 bytes/s, done.
Resolving deltas: 100% (53/53), done.
Checking connectivity... done.
3--
chakib@chakib-temal:~/HIDTESTER$ cd hidapitester
4--
chakib@chakib-temal:~/HIDTESTER/hidapitester$ ls
docs  hidapitester.c  hid_generic_trinketm0  LICENSE  Makefile  ProMicroRawHID  README.md  TeensyRawHid
5--
chakib@chakib-temal:~/HIDTESTER/hidapitester$ sudo make
gcc -I ../hidapi/hidapi -c ../hidapi/linux/hid.c -o ../hidapi/linux/hid.o
gcc -I ../hidapi/hidapi -c hidapitester.c -o hidapitester.o
gcc -I ../hidapi/hidapi ../hidapi/linux/hid.o hidapitester.o -o hidapitester `pkg-config libudev --libs`

there is any problem with my command make ? i don't have any specific terminal opened after this command 
there is a command to open the terminal command hidApitester ? 

Thank's

**Comment by Youw** [comment]
> sudo make

no need for `sudo` here

> there is a command to open the terminal command hidApitester ?

did you `ls` after `make` ?
there should be `hidapitester` in the same folder where `make` was invoked

run it:
```sh
./hidapitester
```
