### ISSUE TITLE
Are there any limitations for keyboards in Windows?

### ISSUE THREAD

**Issue by xcme** [todbot/hidapitester#12]
Hi,
I'm trying to work with my keyboard and this tool can read all properties, but seems it can't read/write data. Doesn't matter what I'm trying, I'm getting only zeroes for reading and -1 for writing. All other HID-related examples I found on github throws out -1 as well, so not sure if I'm doing something wrong or it just impossible.

Is it even possible to read/write data from/to active keyboard in Windows? My goal is to control RGB leds there, relying on [this example](https://github.com/SebiTimeWaster/G213Colors/blob/master/G213Colors.py).

**Comment by mcuee** [comment]
You can not do that since Windows reserves the access to System Keyboard/Mouse.

**Comment by xcme** [comment]
Thank you for the answer. After some research I found the info that Windows separates the functions of the keyboard and mouse their-selves from auxiliary functionality like RGB-backlight. So, when I found the correct 'usage' and 'usage page' I managed to control the leds.
